# Generated by Django 4.1.5 on 2023-02-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
