# Generated by Django 4.1.5 on 2023-02-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(),
        ),
    ]
