# Generated by Django 4.1.5 on 2023-02-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0007_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
