# Generated by Django 4.1.5 on 2023-02-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0010_brand_products_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Availability',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], max_length=100, null=True),
        ),
    ]
