# Generated by Django 4.1.5 on 2023-02-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0011_products_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
