# Generated by Django 4.1.5 on 2023-02-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0012_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
