# Generated by Django 4.1.5 on 2023-02-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0013_order_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='value',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.IntegerField(max_length=6),
        ),
    ]
