# Generated by Django 4.1.5 on 2023-02-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0015_alter_order_phone_alter_order_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='Address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
        migrations.AddField(
            model_name='order',
            name='City',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='First_Name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Last_Name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Mobile_Number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Pin_Code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Quantity',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
