# Generated by Django 4.1.5 on 2023-02-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0017_rename_address_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
