# Generated by Django 4.1.5 on 2023-02-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0018_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Last_Name',
        ),
        migrations.AddField(
            model_name='order',
            name='Full_Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
